export interface lerna_options_type {
	allowBranch:string
	bump:string
	canary:unknown
	contents:unknown
	changelog:unknown
	changelogPreset:unknown
	conventionalCommits:unknown
	conventionalGraduate:unknown
	conventionalPrerelease:unknown
	forcePublish:unknown
	ignoreChanges:unknown
	ignorePrepublish:unknown
	ignoreScripts:unknown
	includeMergedTags:unknown
	legacyAuth:unknown
	message:string
	otp:unknown
	preid:unknown
	private:boolean
	registry:unknown
	rejectCycles:unknown
	requireScripts:boolean
}
